export function buildA2uiProtocolGuide(componentList: string): string {
  return [
    "## A2UI v0.9 协议生成指南",
    "",
    "### 1. 输出外层结构",
    "你的输出必须是一个严格 JSON 对象，不要使用 Markdown 代码块，不要输出 JSON 之外的解释文字。",
    "{",
    '  "assistantMessage": "给用户的文本回复，说明生成或修改了什么",',
    '  "a2uiMessages": []',
    "}",
    "",
    "如果用户只是聊天、解释或询问，并没有要求创建或修改 UI，则 a2uiMessages 必须是空数组 []。",
    "",
    "### 2. 可用组件",
    `只能使用以下 Basic Catalog 组件：${componentList}。`,
    "禁止使用任何 Catalog 外组件，也禁止生成 HTML、JavaScript 或 CSS。",
    "",
    "### 3. 消息类型",
    "a2uiMessages 是 A2UI v0.9 server-to-client 消息数组，每条消息只能是下面四种之一：",
    '1. createSurface: { "version": "v0.9", "createSurface": { "surfaceId": "main", "catalogId": "https://a2ui.org/specification/v0_9/catalogs/basic/catalog.json" } }',
    '2. updateDataModel: { "version": "v0.9", "updateDataModel": { "surfaceId": "main", "path": "/", "value": { ... } } }',
    '3. updateComponents: { "version": "v0.9", "updateComponents": { "surfaceId": "main", "components": [ ... ] } }',
    '4. deleteSurface: { "version": "v0.9", "deleteSurface": { "surfaceId": "main" } }',
    "",
    "生成 UI 时必须先 createSurface，再 updateDataModel（如需要），最后 updateComponents。",
    'surfaceId 固定使用 "main"，catalogId 固定使用 "https://a2ui.org/specification/v0_9/catalogs/basic/catalog.json"。',
    "",
    "### 4. 组件树规则",
    '每个组件对象必须包含：{ "id": "唯一组件ID", "component": "组件类型名称" }。',
    '必须存在一个 id 为 "root" 的组件作为 UI 树根节点。',
    "A2UI 使用邻接表，不使用嵌套 children 对象。容器通过字符串 id 引用子组件。",
    "同一个 surface 内所有组件 id 必须唯一，所有 child/children/tabItems.child 引用的 id 必须真实存在。",
    "",
    "### 5. 常用组件字段",
    '- Text: { "id": "...", "component": "Text", "text": "文本或 { path }", "usageHint": "h1|h2|h3|h4|h5|caption|body" }',
    '- Row: { "id": "...", "component": "Row", "children": ["..."], "distribution": "start|center|end|spaceBetween|spaceAround|spaceEvenly", "alignment": "start|center|end|stretch" }',
    '- Column: { "id": "...", "component": "Column", "children": ["..."], "distribution": "start|center|end|spaceBetween|spaceAround|spaceEvenly", "alignment": "start|center|end|stretch" }',
    '- Card: { "id": "...", "component": "Card", "child": "组件ID" }',
    '- Tabs: { "id": "...", "component": "Tabs", "tabItems": [{ "title": "标签名", "child": "组件ID" }] }',
    '- Button: { "id": "...", "component": "Button", "child": "文本组件ID", "action": { "name": "动作名", "context": { ... } } }',
    '- TextField: { "id": "...", "component": "TextField", "label": "标签", "text": { "path": "/字段" }, "usageHint": "shortText|longText|number|obscured" }',
    '- List: { "id": "...", "component": "List", "children": ["..."], "direction": "vertical|horizontal" }',
    "",
    "### 6. 页面组织方法",
    "不要把页面生成成一串孤立 Text。必须使用容器组件组织层级。",
    "推荐 root 使用 Column，并设置 children、distribution 和 alignment。",
    "页面标题使用独立 Text 组件，usageHint 使用 h1 或 h2。",
    "分区使用 Card 包裹，Card 内部 child 指向一个 Column 或 Row。",
    "信息密集页面（课程表、表单、报表、看板）用 Row 表达横向并列，用 Column 表达纵向内容。",
    "Tabs 页面必须用 tabItems 字段，不要写 tabs 字段。",
    "Card 没有 title 字段；如需卡片标题，在 Card 内部 Column 的第一个子组件放 Text。",
    "",
    "### 7. 数据绑定",
    '动态数据用 JSON Pointer：{ "path": "/some/data/path" }。',
    "Text.text、TextField.text、CheckBox.value、ChoicePicker.value、Slider.value、DateTimeInput.value 等字段可使用 { path }。",
    "如果内容是固定文案，可以直接写字符串，不必放入 dataModel。",
    "",
    "### 8. 常见错误与禁止写法",
    '- 错误：{ "component": "Tabs", "tabs": [...] }。正确：使用 "tabItems"。',
    '- 错误：{ "component": "Card", "title": "标题" }。正确：Card 内部放 Text 标题。',
    '- 错误：Row/Column 的 children 内写完整组件对象。正确：children 只写组件 id 字符串。',
    '- 错误：Button.action 写成字符串。正确：action 必须是 { "name": "...", "context": { ... } }。',
    '- 错误：生成 table、div、input、select、Schedule、Calendar 等 Catalog 外组件。',
    '- 错误：使用 className、style、css、html、innerHTML、script、onClick 等非 Catalog 字段。',
    "",
    "### 9. 标准页面示例",
    "下面示例展示正确的消息顺序、root、容器层级、Tabs.tabItems 和 Card 内标题。实际输出时要按用户需求改内容。",
    "{",
    '  "assistantMessage": "已生成一个课程表预览。",',
    '  "a2uiMessages": [',
    '    { "version": "v0.9", "createSurface": { "surfaceId": "main", "catalogId": "https://a2ui.org/specification/v0_9/catalogs/basic/catalog.json" } },',
    '    { "version": "v0.9", "updateComponents": { "surfaceId": "main", "components": [',
    '      { "id": "root", "component": "Column", "children": ["pageTitle", "scheduleCard"], "distribution": "start", "alignment": "stretch" },',
    '      { "id": "pageTitle", "component": "Text", "text": "我的课表", "usageHint": "h1" },',
    '      { "id": "scheduleCard", "component": "Card", "child": "scheduleContent" },',
    '      { "id": "scheduleContent", "component": "Column", "children": ["cardTitle", "weekTabs"], "distribution": "start", "alignment": "stretch" },',
    '      { "id": "cardTitle", "component": "Text", "text": "本周课程", "usageHint": "h2" },',
    '      { "id": "weekTabs", "component": "Tabs", "tabItems": [',
    '        { "title": "周一", "child": "mondayList" },',
    '        { "title": "周二", "child": "tuesdayList" }',
    "      ] },",
    '      { "id": "mondayList", "component": "Column", "children": ["mon1", "monDivider", "mon2"], "distribution": "start", "alignment": "stretch" },',
    '      { "id": "mon1", "component": "Text", "text": "08:00-09:40 高等数学", "usageHint": "body" },',
    '      { "id": "monDivider", "component": "Divider" },',
    '      { "id": "mon2", "component": "Text", "text": "10:00-11:40 大学英语", "usageHint": "body" },',
    '      { "id": "tuesdayList", "component": "Column", "children": ["tue1"], "distribution": "start", "alignment": "stretch" },',
    '      { "id": "tue1", "component": "Text", "text": "08:00-09:40 线性代数", "usageHint": "body" }',
    "    ] } }",
    "  ]",
    "}",
  ].join("\n");
}
